apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: cards
  name: cards
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: cards
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: cards
    spec:
      containers:
        - env:
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              value: http://eurekaserver:8761/eureka/
            - name: SERVER_ADDRESS
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "9000"
            - name: SPRING_APPLICATION_NAME
              value: cards
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071/
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/eazybank_cards
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_PROFILES_ACTIVE
              value: prod
          image: achrefloussaief101/cards
          name: cards
          ports:
            - containerPort: 9000
              protocol: TCP
      restartPolicy: Always
