apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.36.0 (ae2a39403)
  labels:
    io.kompose.service: eurekaserver
  name: eurekaserver
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: eurekaserver
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.36.0 (ae2a39403)
      labels:
        io.kompose.service: eurekaserver
    spec:
      containers:
        - env:
            - name: SERVER_ADDRESS
              value: 0.0.0.0
            - name: SERVER_PORT
              value: "8761"
            - name: SPRING_CONFIG_IMPORT
              value: optional:configserver:http://configserver:8071/
            - name: SPRING_PROFILES_ACTIVE
              value: default
          image: eurekaserver
          name: eurekaserver
          ports:
            - containerPort: 8761
              protocol: TCP
      restartPolicy: Always
