apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-build
spec:
  template:
    spec:
      containers:
        - name: prepare
          image: ubuntu:latest
          command: ["/bin/bash", "-c", "chmod +x /app/prepare-build.sh && /app/prepare-build.sh"]
          volumeMounts:
            - name: script-volume
              mountPath: /app
      restartPolicy: Never
      volumes:
        - name: script-volume
          configMap:
            name: prepare-script
  backoffLimit: 3