server:
  port: 8080

spring:
  application:
    name: accounts
  config:
    import: optional:configserver:http://localhost:8071/
    fail-fast: true
    retry:
      initial-interval: 2000
      max-attempts: 6
      multiplier: 1.5

  datasource:
    url: jdbc:postgresql://localhost:5432/eazybank_accounts
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"

build:
  version: 1.0.0
