events {}

http {
  upstream accounts {
    server accounts:8080;
  }

  upstream cards {
    server cards:9000;
  }

  upstream loans {
    server loans:9001;
  }

  server {
    listen 80;

    location /accounts/ {
      proxy_pass http://accounts/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /cards/ {
      proxy_pass http://cards/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /loans/ {
      proxy_pass http://loans/;
      proxy_set_header Host $host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
  }
}